framework:
    workflows:
        notification:
            type: 'workflow'
            audit_trail:
                enabled: true
            initial_marking: created
            supports:
                - App\NotificationModule\Entity\Notification
                - App\WorkflowModule\Contract\WorkflowSubjectInterface
            places:
                - created
                - queued
                - pending
                - sent
                - delivered
                - failed
                - acknowledged
                - opened
                - archived
            transitions:
                queue:
                    from: created
                    to: queued
                prepare:
                    from: queued
                    to: pending
                send:
                    from: pending
                    to: sent
                deliver:
                    from: sent
                    to: delivered
                fail:
                    from: sent
                    to: failed
                acknowledge:
                    from: delivered
                    to: acknowledged
                open:
                    from: delivered
                    to: opened
                archive:
                    from: [delivered, failed, acknowledged, opened]
                    to: archived

        circuit_breaker:
            type: 'state_machine'
            marking_store:
                service: App\WorkflowModule\Store\CacheCircuitBreakerStore
            audit_trail:
                enabled: true
            initial_marking: closed
            supports:
                - App\Contracts\CircuitBreakerInterface
            places:
                - closed
                - open
                - half_open
            transitions:
                trip:
                    from: closed
                    to:   open
                probe:
                    from: open
                    to:   half_open
                reset:
                    from: [half_open, open]
                    to:   closed